### ISSUE TITLE
Design QA Refreshed

### ISSUE THREAD

**Issue by cgcarter25** [earthrise-media/vacs-map#95]
Another round of even smaller notes!

_**Desktop**_

**Landing page**

- [x] Remove the dark stroke at the top of the VACS pop up
- [x] Confirm pop up border radius is 16 px
- [x] The “X” and the links should both be #8CA4CB for the pop up

**Crop card**

- [x] Header question navigates back to landing page
- [x] Possible to make it so none of Africa is getting cut off? nbd if not
- [ ] Add categories to the descriptions with these hex codes (low: #FFA31A, medium: #E5C659, high: #34A853, no data?: #7E899C)

**Map page**

- [x] Header question navigates back to landing page
- [x] Cut the padding below the header question to 1/3 of what it currently is, and make the opacity of the background 70%
- [x] Confirm pop up border radius is 16 px
- [x] The “X” should be #8CA4CB for the pop up
- [x] When you hover over a segment and get the title in the left hand column, make that text have less line-height (110%)
- [x] Possible to make the fingerprint categories hoverable? So if you hover over “genetic” everything else is knocked back in opacity for example?
- [x] Add gray italic text about the benchmark crop below header like in this [mock](https://www.figma.com/file/o3LQntPkm5yC5SqSX6nGn3/Design?type=design&node-id=511%3A1989&mode=design&t=ebvbGLJlxgDHQtW3-1)
- [x] Change the emissions button text to “Low Emissions – SSP126” and “High Emissions – SSP370”
- [x] Update Add layer button to be 40px diameter
- [x] Reduce space between add layer and the zoom by half
- [ ] When you hover over a button on the minimap would it be possible to bring that button to the top of the pile of buttons so the stroke is called out a bit more?
- [x] Confirm url validation font is 16

_**Mobile**_

**Landing page**

- [x] Bottom half of the logos get cut off in safari
- [x] Half margin space on pop up margins and confirm “X” and links are #8CA4CB in pop up
- [x] Add space (like between other paragraphs) between learn more button and paragraph before it
- [x] the video scrolls, possible to have it fixed?

**Crop card**

- [ ] When I hit “find out” the soybean info text opens and stays open
- [x] Move the link validation url to appear above the buttons when I copy a link

**Map page**

- [x] legend is getting cut off in safari
- [x] Half margin space on pop up margins and confirm “X” and links are #8CA4CB in pop up
- [x] Make the line height of the header for the pop ups 11-%
- [x] Move zoom buttons lower

**Comment by mwbernard** [comment]
> When I hit “find out” the soybean info text opens and stays open 

- I think this is due to the way touches are interpreted like hover by screens, and when the cards load on your phone that label is where you were touching.

> When you hover over a button on the minimap would it be possible to bring that button to the top of the pile of buttons so the stroke is called out a bit more? 

- As I mentioned before this one's a little tougher

> Add categories to the descriptions with these hex codes (low: #FFA31A, medium: #E5C659, high: #34A853, no data?: #7E899C)

- Covering this in #90
